/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoriySonRouteImport } from './routes/joriy-son'
import { Route as ForAuthorsRouteImport } from './routes/for-authors'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArxivIndexRouteImport } from './routes/arxiv.index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedSubmissionsIndexRouteImport } from './routes/_authenticated/submissions.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ArxivJildSonRouteImport } from './routes/arxiv.$jild.$son'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedEditorQueueRouteImport } from './routes/_authenticated/editor.queue'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin.tools'
import { Route as AuthenticatedAdminStatisticsRouteImport } from './routes/_authenticated/admin.statistics'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminIssuesRouteImport } from './routes/_authenticated/admin.issues'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin.inbox'
import { Route as AuthenticatedAdminDoisRouteImport } from './routes/_authenticated/admin.dois'
import { Route as AuthenticatedSubmissionsIdIndexRouteImport } from './routes/_authenticated/submissions.$id.index'
import { Route as AuthenticatedSubmissionsIdEditRouteImport } from './routes/_authenticated/submissions.$id.edit'

const JoriySonRoute = JoriySonRouteImport.update({
  id: '/joriy-son',
  path: '/joriy-son',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAuthorsRoute = ForAuthorsRouteImport.update({
  id: '/for-authors',
  path: '/for-authors',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArxivIndexRoute = ArxivIndexRouteImport.update({
  id: '/arxiv/',
  path: '/arxiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsIndexRoute =
  AuthenticatedSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArxivJildSonRoute = ArxivJildSonRouteImport.update({
  id: '/arxiv/$jild/$son',
  path: '/arxiv/$jild/$son',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditorQueueRoute =
  AuthenticatedEditorQueueRouteImport.update({
    id: '/editor/queue',
    path: '/editor/queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin/tools',
  path: '/admin/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStatisticsRoute =
  AuthenticatedAdminStatisticsRouteImport.update({
    id: '/admin/statistics',
    path: '/admin/statistics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIssuesRoute =
  AuthenticatedAdminIssuesRouteImport.update({
    id: '/admin/issues',
    path: '/admin/issues',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDoisRoute = AuthenticatedAdminDoisRouteImport.update({
  id: '/admin/dois',
  path: '/admin/dois',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsIdIndexRoute =
  AuthenticatedSubmissionsIdIndexRouteImport.update({
    id: '/submissions/$id/',
    path: '/submissions/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsIdEditRoute =
  AuthenticatedSubmissionsIdEditRouteImport.update({
    id: '/submissions/$id/edit',
    path: '/submissions/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/for-authors': typeof ForAuthorsRoute
  '/joriy-son': typeof JoriySonRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/arxiv/': typeof ArxivIndexRoute
  '/admin/dois': typeof AuthenticatedAdminDoisRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/editor/queue': typeof AuthenticatedEditorQueueRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/arxiv/$jild/$son': typeof ArxivJildSonRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/submissions/$id/edit': typeof AuthenticatedSubmissionsIdEditRoute
  '/submissions/$id/': typeof AuthenticatedSubmissionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/for-authors': typeof ForAuthorsRoute
  '/joriy-son': typeof JoriySonRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/arxiv': typeof ArxivIndexRoute
  '/admin/dois': typeof AuthenticatedAdminDoisRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/editor/queue': typeof AuthenticatedEditorQueueRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/arxiv/$jild/$son': typeof ArxivJildSonRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/submissions': typeof AuthenticatedSubmissionsIndexRoute
  '/submissions/$id/edit': typeof AuthenticatedSubmissionsIdEditRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/for-authors': typeof ForAuthorsRoute
  '/joriy-son': typeof JoriySonRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/arxiv/': typeof ArxivIndexRoute
  '/_authenticated/admin/dois': typeof AuthenticatedAdminDoisRoute
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/editor/queue': typeof AuthenticatedEditorQueueRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/arxiv/$jild/$son': typeof ArxivJildSonRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/_authenticated/submissions/$id/edit': typeof AuthenticatedSubmissionsIdEditRoute
  '/_authenticated/submissions/$id/': typeof AuthenticatedSubmissionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bootstrap'
    | '/for-authors'
    | '/joriy-son'
    | '/audit'
    | '/dashboard'
    | '/arxiv/'
    | '/admin/dois'
    | '/admin/inbox'
    | '/admin/issues'
    | '/admin/reports'
    | '/admin/statistics'
    | '/admin/tools'
    | '/admin/users'
    | '/editor/queue'
    | '/settings/profile'
    | '/arxiv/$jild/$son'
    | '/admin/'
    | '/submissions/'
    | '/submissions/$id/edit'
    | '/submissions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bootstrap'
    | '/for-authors'
    | '/joriy-son'
    | '/audit'
    | '/dashboard'
    | '/arxiv'
    | '/admin/dois'
    | '/admin/inbox'
    | '/admin/issues'
    | '/admin/reports'
    | '/admin/statistics'
    | '/admin/tools'
    | '/admin/users'
    | '/editor/queue'
    | '/settings/profile'
    | '/arxiv/$jild/$son'
    | '/admin'
    | '/submissions'
    | '/submissions/$id/edit'
    | '/submissions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/bootstrap'
    | '/for-authors'
    | '/joriy-son'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/arxiv/'
    | '/_authenticated/admin/dois'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/issues'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/statistics'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/users'
    | '/_authenticated/editor/queue'
    | '/_authenticated/settings/profile'
    | '/arxiv/$jild/$son'
    | '/_authenticated/admin/'
    | '/_authenticated/submissions/'
    | '/_authenticated/submissions/$id/edit'
    | '/_authenticated/submissions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BootstrapRoute: typeof BootstrapRoute
  ForAuthorsRoute: typeof ForAuthorsRoute
  JoriySonRoute: typeof JoriySonRoute
  ArxivIndexRoute: typeof ArxivIndexRoute
  ArxivJildSonRoute: typeof ArxivJildSonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/joriy-son': {
      id: '/joriy-son'
      path: '/joriy-son'
      fullPath: '/joriy-son'
      preLoaderRoute: typeof JoriySonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-authors': {
      id: '/for-authors'
      path: '/for-authors'
      fullPath: '/for-authors'
      preLoaderRoute: typeof ForAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arxiv/': {
      id: '/arxiv/'
      path: '/arxiv'
      fullPath: '/arxiv/'
      preLoaderRoute: typeof ArxivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/': {
      id: '/_authenticated/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AuthenticatedSubmissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/arxiv/$jild/$son': {
      id: '/arxiv/$jild/$son'
      path: '/arxiv/$jild/$son'
      fullPath: '/arxiv/$jild/$son'
      preLoaderRoute: typeof ArxivJildSonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor/queue': {
      id: '/_authenticated/editor/queue'
      path: '/editor/queue'
      fullPath: '/editor/queue'
      preLoaderRoute: typeof AuthenticatedEditorQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/admin/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/statistics': {
      id: '/_authenticated/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AuthenticatedAdminStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/issues': {
      id: '/_authenticated/admin/issues'
      path: '/admin/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AuthenticatedAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dois': {
      id: '/_authenticated/admin/dois'
      path: '/admin/dois'
      fullPath: '/admin/dois'
      preLoaderRoute: typeof AuthenticatedAdminDoisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/$id/': {
      id: '/_authenticated/submissions/$id/'
      path: '/submissions/$id'
      fullPath: '/submissions/$id/'
      preLoaderRoute: typeof AuthenticatedSubmissionsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/$id/edit': {
      id: '/_authenticated/submissions/$id/edit'
      path: '/submissions/$id/edit'
      fullPath: '/submissions/$id/edit'
      preLoaderRoute: typeof AuthenticatedSubmissionsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminDoisRoute: typeof AuthenticatedAdminDoisRoute
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminIssuesRoute: typeof AuthenticatedAdminIssuesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStatisticsRoute: typeof AuthenticatedAdminStatisticsRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedEditorQueueRoute: typeof AuthenticatedEditorQueueRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedSubmissionsIndexRoute: typeof AuthenticatedSubmissionsIndexRoute
  AuthenticatedSubmissionsIdEditRoute: typeof AuthenticatedSubmissionsIdEditRoute
  AuthenticatedSubmissionsIdIndexRoute: typeof AuthenticatedSubmissionsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminDoisRoute: AuthenticatedAdminDoisRoute,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminIssuesRoute: AuthenticatedAdminIssuesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStatisticsRoute: AuthenticatedAdminStatisticsRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedEditorQueueRoute: AuthenticatedEditorQueueRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedSubmissionsIndexRoute: AuthenticatedSubmissionsIndexRoute,
  AuthenticatedSubmissionsIdEditRoute: AuthenticatedSubmissionsIdEditRoute,
  AuthenticatedSubmissionsIdIndexRoute: AuthenticatedSubmissionsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BootstrapRoute: BootstrapRoute,
  ForAuthorsRoute: ForAuthorsRoute,
  JoriySonRoute: JoriySonRoute,
  ArxivIndexRoute: ArxivIndexRoute,
  ArxivJildSonRoute: ArxivJildSonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
